brew "yadm"
brew "tmux"
brew "vim"
brew "zsh"
brew "git"
brew "uv"
brew "ripgrep"
brew "starship"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "firefox"
cask "visual-studio-code"
cask "meetingbar"
cask "launchbar"
