brew "yadm"
brew "tmux"
brew "vim"
brew "zsh"
brew "git"
brew "uv"
brew "ripgrep"
brew "starship"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "zsh-completions"

cask "firefox"
cask "visual-studio-code"
cask "meetingbar"
cask "raycast"
cask "font-fira-code-nerd-font"