repos:
  - repo: https://github.com/crate-ci/typos
    rev: v1.49.0
    hooks:
      - id: typos
        args: [--force-exclude]
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: prettier --write
        language: node
        additional_dependencies: ["prettier@3.3.3"]
        types: [markdown]
