#!/bin/sh

set -e

echo "Installing brew bundle (if brew is installed)"
command -v brew && brew bundle install --global

echo "Updating Vim plugins"
curl -s -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim -c PlugInstall -c PlugUpdate -c qa
