#!/bin/sh

set -x
set -e

git clone --depth=1 https://github.com/robbyrussell/oh-my-zsh.git "${HOME}/.oh-my-zsh" || git -C "${HOME}/.oh-my-zsh" pull

git clone --depth=1 https://github.com/Bash-it/bash-it.git "${HOME}/.bash_it" || git -C "${HOME}/.bash_it" pull

yadm -C "${HOME}" submodule update --init

curl -s -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim -c PlugInstall -c PlugUpdate -c qa
