onboarding = false

[ui]
show_agent_labels_on_pane_borders = true
prompt_new_tab_name = false
hide_tab_bar_when_single_tab = true

agent_panel_sort = "priority"

[ui.sidebar.spaces]
row_gap = 1

[ui.sound]
enabled = true

[ui.toast]
delivery = "terminal"

[ui.toast.clipboard]
enabled = false

[theme]
name = "tokyo-night"
auto_switch = false
